# DATABASE
DATABASE = '../project_database'

# COMMANDS
LIST_USERS = '/users'
LIST_USERS_METHOD = 'GET'

# DISPLAY USERS
DISPLAY_USER = '/<uname>'
DISPLAY_USER_METHOD = 'GET'

# ADD USER
ADD_USER = '/add/<uname>/<pay>'
ADD_USER_METHOD = 'GET'

# REMOVE USER
RMV_USER = '/rmv/<uname>'
RMV_USER_METHOD = 'GET'

# LIST ALL TRANSACTIONS
LIST_TRANSACTIONS = '/transactions'
LIST_TRANSACTIONS_METHOD = 'GET'

# LIST ALL TRANSACTIONS RELATIVE TO AN USER
USER_TRANSACTIONS = '/<user>/transactions'
USER_TRANSACTIONS_METHOD = 'GET'

# ADD A TRANSACTION
ADD_TRANSACTIONS = '/add/<source>/<recipient>/<amount>'
ADD_TRANSACTIONS_METHOD = 'GET'

# CREATE THE DATABASE
CREATE_DATABASE = '/create_database'
CREATE_DATABASE_METHOD = 'GET'

# CHECK HASK OF TRANSACTIONS
HASH_CHECK = '/check_hash'
HASH_CHECK_METHOD = 'GET'
