#!/bin/bash

DATABASE_NAME=project_database
SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $SCRIPTPATH
cd ..

echo "Ex 7 - Test 1: UPDATING AMOUNT OF TRANSACTION N°4."
test1=$(sqlite3 $DATABASE_NAME "UPDATE trans SET amount=9999 WHERE id=4;")
if [[ $test1 = "" ]]
then
    echo Successfully attacked.
else
    echo Attack failed.
fi